ARG VERSION=3.1
FROM mcr.microsoft.com/dotnet/core/aspnet:$VERSION

RUN apt-get update \
  && apt-get install -y --no-install-recommends unzip \
  && apt-get install -y procps \
  && rm -rf /var/lib/apt/lists/* \ 
  && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

EXPOSE 4024
EXPOSE 3702