ARG SDK_VERSION=3.1
FROM mcr.microsoft.com/dotnet/sdk:${SDK_VERSION} as sdk-image
FROM sdk-image as sdk
WORKDIR /source
 
RUN apt-get update
RUN apt-get install mono-complete -y

ARG BUILD_CONFIGURATION_ARG=release
ENV BUILD_CONFIGURATION ${BUILD_CONFIGURATION_ARG}
ENV BUILD_ENV docker

RUN mkdir .config
ONBUILD COPY .config/dotnet-tools.json .config/
ONBUILD RUN dotnet tool restore


